package structs

import (
	"encoding/json"
	"io"
	"io/ioutil"
)

type DataStruct struct {
	ProjectPath        string
	NeedAuthentication bool
	Config             ConfigStruct
	Models             []ModelStruct
}

type ConfigStruct struct {
	Port        string
	DB_TYPE     string
	DB_USERNAME string
	DB_PASSWORD string
	DB_HOST     string
	DB_PORT     string
	DB_NAME     string
}

type ModelStruct struct {
	Name   string
	Fields []FieldStruct
}

type FieldStruct struct {
	Name                   string
	Type                   string
	Required               bool
	Default                string
	Unique                 bool
	AutoGenerated          bool
	Max                    int
	Min                    int
	AuthenticationUsername bool
	AuthenticationPassword bool
}

func ParseBody(body io.ReadCloser) (DataStruct, error) {
	bodyBytes, _ := ioutil.ReadAll(body)

	DataStruct := DataStruct{}
	err := json.Unmarshal(bodyBytes, &DataStruct)

	return DataStruct, err
}

/*
{
	"config": {
		"db_type": "MYSQL",
		"db_username": "username",
		"db_password": "password",
		"db_host": "host",
		"db_port": "port",
		"db_name": "name"
	},
	"models": [{
			"name": "User",
			"fields": [{
					"name": "username",
					"type": "string",
					"required": true,
					"default": "asd",
					"unique": true,
					"autogenerated": true
				},
				{
					"name": "password",
					"type": "string",
					"required": false,
					"default": "",
					"unique": false,
					"autogenerated": false
				}
			]
		},
		{
			"name": "Product",
			"fields": [{
					"name": "name",
					"type": "string",
					"required": true,
					"default": "asd",
					"unique": true,
					"autogenerated": true
				},
				{
					"name": "quantity",
					"type": "int",
					"required": false,
					"default": "3",
					"unique": true,
					"autogenerated": false
				},
				{
					"name": "available",
					"type": "bool",
					"required": false,
					"default": "true",
					"unique": false,
					"autogenerated": false
				}
			]
		}
	]
}
*/
